### ISSUE TITLE
add features to enable aws/azure/gcp support to object_store

### ISSUE THREAD

**Issue by nicklan** [delta-incubator/delta-kernel-rs#135]
Right now we don't expose such features meaning you can't actually use these without editing Cargo.toml

**Comment by nfoerster2** [comment]
is there any update, is azure supported or not?

**Comment by nicklan** [comment]
azure is supported if you enable the `cloud` feature. you'll need to construct the `DefaultEngine` with the proper keys for authentication. These are passed through to object store, so they are [these ones](https://docs.rs/object_store/latest/object_store/azure/enum.AzureConfigKey.html)
