### ISSUE TITLE
Explore providing a ColumnarBatch like trait

### ISSUE THREAD

**Issue by rtyler** [delta-incubator/delta-kernel-rs#21]
This issue is to capture the work of determining how feasible it would be to remove our `arrow::RecordBatch` dependency and replace it with something akin to the `ColumnarBatch` interface [implemented in the JVM kernel implementation](https://github.com/delta-io/delta/blob/master/kernel/kernel-api/src/main/java/io/delta/kernel/data/ColumnarBatch.java)

The goal for this ticket is to provide an interface which would allow `default-client` to rely on an `arrow::RecordBatch` implementation of `ColumnarBatch` that makes sense in some form.

**Comment by nicklan** [comment]
closing as we've settled on #109
