### ISSUE TITLE
have `GlobalScanState` just have `SchemaRef`s and implement custom ser/deser

### ISSUE THREAD

**Issue by nicklan** [delta-incubator/delta-kernel-rs#216]
Currently `GlobalScanState` has the variable `logical_schema` and `read_schema` as type `Schema`. This allows us to just do  `#[derive(Serialize, Deserialize)]`, but also requires us to clone (potentially large) schema in order to construct state.

Rather, let's make them `SchemaRef` (an `Arc`), and do our own implementations of `Serialize` and `Deserialize` that can just get inside the arc and "do the right thing"

**Comment by abrassel** [comment]
Mind if I grab this? @nicklan

**Comment by nicklan** [comment]
> Mind if I grab this? @nicklan 

Sure, go for it thanks.

**Comment by abrassel** [comment]
@nicklan do you mind answering what the global scan state is at a high level?

**Comment by abrassel** [comment]
Also, @nicklan , I see that we have
```
pub enum DataType {
    /// UTF-8 encoded string of characters
    Primitive(PrimitiveType),
    /// An array stores a variable length collection of items of some type.
    Array(Box<ArrayType>),
    /// A struct is used to represent both the top-level schema of the table as well
    /// as struct columns that contain nested columns.
    Struct(Box<StructType>),
    /// A map stores an arbitrary length collection of key-value pairs
    /// with a single keyType and a single valueType
    Map(Box<MapType>),
}
```

But now we get `Arc<StructType>` sometimes. This suggests that DataType might be too specific about the ownership model for its variants. 

We have a couple of options:
* Ditch the Arc - do we really need reference counted shared ownership? 
* Brute force the Arc into a Box (at the cost of an extra clone). I've gone ahead and done that for this PR. It's kind of ugly
* Make the `DataType` enum generic over ownership model: `AsRef<...>` either through monomorphisizing or vtabling.
* Ditch the Box and always use `Arc`. 

I don't yet have sufficient context on the `delta-kernel-rs` project to make a judgement call. What do you think?

**Comment by scovich** [comment]
>  we have
>
> ```rust
> pub enum DataType {
>       ...
>     /// A struct is used to represent both the top-level schema of the table as well
>     /// as struct columns that contain nested columns.
>     Struct(Box<StructType>),
>       ...
> }
> ```
> But now we get `Arc<StructType>` sometimes. This suggests that `DataType` might be too specific about the ownership model for its variants.
>
> [We could] Brute force the `Arc` into a `Box` (at the cost of an extra clone). I've gone ahead and done that for this PR. It's kind of ugly.

Maybe I missed some context, but when do we need to turn a `SchemaRef` directly into a `DataType` without any transformations? 

Meanwhile it seems like [Arc::unwrap_or_clone](https://doc.rust-lang.org/std/sync/struct.Arc.html#method.unwrap_or_clone) might be superior to plain `clone`, if we're able to consume the `Arc`?

**Comment by scovich** [comment]
>  when do we need to turn a SchemaRef directly into a DataType without any transformations?

Found it here in [scan/mod.rs](https://github.com/delta-incubator/delta-kernel-rs/blob/4e6927cced9077c26ccc45e2fde28ca34c2ab1d5/kernel/src/scan/mod.rs#L247)

**Comment by abrassel** [comment]
both good suggestions. i'm underwater at work but i'll work on this when I get a chance!

**Comment by abrassel** [comment]
@nicklan this issue should be ready to be closed

**Comment by nicklan** [comment]
Done in #229
