### ISSUE TITLE
`MetadataValue` schema doesn't support nested values, used by IcebergCompatV2 protocol

### ISSUE THREAD

**Issue by jeppe742** [delta-incubator/delta-kernel-rs#253]
When you create a delta table with Uniform enabled it will create a delta transaction that looks something like this

```json
{"commitInfo":{"timestamp":1717753754287,"operation":"CREATE TABLE","operationParameters":{"isManaged":"true","description":null,"partitionBy":"[]","properties":"{\"delta.enableIcebergCompatV2\":\"true\",\"delta.universalFormat.enabledFormats\":\"iceberg\",\"delta.columnMapping.mode\":\"name\",\"delta.columnMapping.maxColumnId\":\"1\"}"},"isolationLevel":"Serializable","isBlindAppend":true,"operationMetrics":{},"engineInfo":"Apache-Spark/3.5.1 Delta-Lake/3.1.0","txnId":"a4d4593f-835c-4d00-81d8-27c1103343d2"}}
{"metaData":{"id":"a8477f73-f004-4a08-8397-3420d4df98a2","format":{"provider":"parquet","options":{}},"schemaString":"{\"type\":\"struct\",\"fields\":[{\"name\":\"c1\",\"type\":\"integer\",\"nullable\":true,\"metadata\":{\"delta.columnMapping.id\":1,\"delta.columnMapping.nested.ids\":{},\"delta.columnMapping.physicalName\":\"col-fdc375c2-e5f2-44c5-a5e9-2cdafca1ddfd\"}}]}","partitionColumns":[],"configuration":{"delta.enableIcebergCompatV2":"true","delta.universalFormat.enabledFormats":"iceberg","delta.columnMapping.mode":"name","delta.columnMapping.maxColumnId":"1"},"createdTime":1717753754108}}
{"protocol":{"minReaderVersion":2,"minWriterVersion":7,"writerFeatures":["columnMapping","icebergCompatV2"]}}
```

Notice that the metaData.schemaString.metadata property has the following metadata

```json
{
    "metadata": {
        "delta.columnMapping.id": 1,
        "delta.columnMapping.nested.ids": {},
        "delta.columnMapping.physicalName": "col-fdc375c2-e5f2-44c5-a5e9-2cdafca1ddfd"
    }
}
```

Currently the schema parser only expects a number, string or boolean, but not a nested struct like we have for `"delta.columnMapping.nested.ids": {}`
https://github.com/delta-incubator/delta-kernel-rs/blob/823367e4dc13b627914412ee2ca7933a1c7b822a/kernel/src/schema.rs#L20-L24

This causes all delta tables written with Iceberg enabled through Uniform, to be unreadable with the kernel. (See https://github.com/delta-io/delta-rs/issues/2578)

**Comment by nicklan** [comment]
Thanks for the report. #257 should fix this!

**Comment by jeppe742** [comment]
Thanks @nicklan !
Just out of curiosity, do we have an idea when this will be included in a new release? 😃

**Comment by nicklan** [comment]
I need to verify that we haven't changed any APIs, but assuming we haven't, I'll get a 0.1.2 release out this week with this and a few other fixes.

**Comment by nicklan** [comment]
@jeppe742 sorry for the long delay! we did change APIs so I needed to do a 0.2.0 release, but it's now out with this included.
