### ISSUE TITLE
Public release goals

### ISSUE THREAD

**Issue by wjones127** [delta-incubator/delta-kernel-rs#42]
Goals:

 * [x] Support reading delta tables
     * Including deletion vectors, column mapping
     * Support single threaded, multiple process, multiple threads cases
 * [x] #46
 * [x] We have easy instructions to pull C library as a dependency.
 * [x] We have documentation for the C API
 * [x] DuckDB prototype
 * [x] Documentation for architecture vision

Low priority:
 * [x] Expression API and file skipping support
 * [x] A C++ library wrapping C FFI with read support as described above

See [Initial Release Milestone](https://github.com/delta-incubator/delta-kernel-rs/milestone/1) for issues

**Comment by nicklan** [comment]
Public release has happened, and in retrospect all this got done :)

:woo:
