### ISSUE TITLE
Add logging or tracing

### ISSUE THREAD

**Issue by wjones127** [delta-incubator/delta-kernel-rs#62]
@nicklan proposed adding logging via the [log](https://crates.io/crates/log) crate.

It seems like a good idea to add some sort of observability capability.

Based on my experience in Rust, it's far more useful to have `tracing`. This crate has logging capabilities, but also the ability to emit spans. The [tracing](https://crates.io/crates/tracing) crate does a good job of this.

## Dependency / performance impact

It was asked in the meeting what the performance impact would be. The answer is that adding these dependencies on its own does not change the output binary. Libraries are expected to use the macros to add logs and spans, but not instantiate any subscriber to them. Without a subscriber these logs and spans are no-ops at compile time, and will be optimized away. However, if an application using kernel registers a subscriber, they will generate code to record the events.

**Comment by nicklan** [comment]
We're using `tracing` now
