### ISSUE TITLE
Checkpoint actions don't need to be tracked in the log replay hashmap

### ISSUE THREAD

**Issue by ryan-johnson-databricks** [delta-incubator/delta-kernel-rs#70]
Currently, we don't distinguish between actions that came from deltas vs. checkpoint, which bloats the hash table used to track and deduplicate versions in [file_stream.rs](https://github.com/nicklan/delta-kernel-rs/blob/main/kernel/src/scan/file_stream.rs#L92).

We need the hash table to track actions from deltas, that we've already seen and which may have older versions in older deltas and/or checkpoint... but checkpoint actions are already "oldest" and so we don't need to track them.

**Comment by scovich** [comment]
This appears to have been solved some time ago by the introduction of the `is_log_batch` parameter in the input stream.

**Comment by zachschuermann** [comment]
yup - thanks for the cleanup!
