### ISSUE TITLE
Snapshot P&M is not optional

### ISSUE THREAD

**Issue by ryan-johnson-databricks** [delta-incubator/delta-kernel-rs#75]
`Snapshot::read_metadata` currently returns `Option<Metadata, Protocol>`, but those are not optional. 
A table whose replay lacks either or both is ill-formed and should always produce an error.

See Delta spec for [Action reconciliation](https://github.com/delta-io/delta/blob/master/PROTOCOL.md#action-reconciliation):
> A given snapshot of a Delta table consists of:
> * A single protocol action
> * A single metaData action

**Comment by nicklan** [comment]
Done by #80
